apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2allow-auditor
  labels:
    k8s-app: kube2allow
    component: auditor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube2allow-auditor
  labels:
    k8s-app: kube2allow
    component: auditor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kube2allow-auditor
  namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2allow-auditor
  labels:
    k8s-app: kube2allow
    component: auditor
spec:
  selector:
    matchLabels:
      k8s-app: kube2allow
      component: auditor
  template:
    metadata:
      labels:
        k8s-app: kube2allow
        component: auditor
    spec:
      serviceAccountName: kube2allow-auditor
      hostPID: true
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube2allow-auditor
        image: sigbilly/kube2allow:latest
        command: ["/usr/local/bin/python"]
        args: ["/app.py"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
